version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
    allow:
      - dependency-type: all
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /robotics_integration_tests/custom_images/migrations_runner
    schedule:
      interval: weekly
    ignore:
      - dependency-name: dotnet/sdk
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /robotics_integration_tests/custom_images/teams_webhook_receiver
    schedule:
      interval: weekly
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major
