[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robotics-integration-tests"
version = "1.0.0"
description = "Internal reusable integration test harness"
requires-python = ">=3.14"
dependencies = [
  "pytest",
  "testcontainers[postgres,azurite,mqtt]",
    "azure-storage-blob",
    "pydantic",
    "pydantic-settings",
    "loguru",
    "python-dotenv",
    "requests",
    "paho-mqtt>=2.1.0"
]

[project.optional-dependencies]
dev = [
    "black"
]

[tool.setuptools.packages.find]
where = ["robotics_integration_tests"]

[dependency-groups]
dev = [
    "pytest-xdist>=3.8.0",
]
