name: Compile Requirements

on:
  workflow_call:
    inputs:
      project_name:
        description: "Path to pyproject.toml file"
        required: false
        type: string
        default: "."

# Permissions must be provided from calling workflow
permissions:
  contents: write
  pull-requests: write

jobs:
  compile-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b #v8.1.0
        with:
          enable-cache: true

      - name: Upgrade uv.lock
        run: |
          uv lock --upgrade --project ${{ inputs.project_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 #v8
        with:
          commit-message: "GHA: Update dependencies"
          title: Update dependencies
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          labels: automated-pr
          delete-branch: true
